DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(

USERNAME VARCHAR(250) NOT NULL PRIMARY KEY,
PASSWORD VARCHAR (512) NOT NULL,
ENABLED BOOLEAN NOT NULL


);

DROP TABLE IF EXISTS AUTHORITIES;

CREATE TABLE AUTHORITIES(
USERNAME VARCHAR(250) NOT NULL,
AUTHORITY VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT(

ID MEDIUMINT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(250) NOT NULL,
PRICE DOUBLE NOT NULL,
DESCRIPTION VARCHAR(250) NOT NULL,
CATEGORY VARCHAR(250) NOT NULL,

PRIMARY KEY (ID)


);

DROP TABLE IF EXISTS ORDERS;

CREATE TABLE ORDERS(

ORDER_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
ORDERS_NAME VARCHAR (250),
TOTAL_PRICE DOUBLE NOT NULL,
PAYMENT_TYPE VARCHAR (250) NOT NULL,
ORDER_DATE TIMESTAMP

);





